Repository Panenco/panenco-ui, pull requests merged in 2022-08, with the labels that each got.

#334 fix: day picker disabled state
  src/components/form/day-picker/index.tsx
Labels: improvement

#335 fix: icon readme typo
  src/components/icon/README.md
Labels: documentation, invalid

#341 fix: add ability to use custom sortIcons in table
  src/components/icon/index.tsx
  src/components/responsive-table/header-cell.tsx
  src/components/responsive-table/types.ts
Labels: enhancement
