Repository Panenco/panenco-ui, pull requests merged in 2022-10, with the labels that each got.

#350 fix: auto menuPlacement to select and new styles
  src/components/select/select-component.tsx
  src/components/select/style.ts
Labels: UI, improvement

#356 feat: yarn v1 -> v3
  .github/workflows/main.yml
  .gitignore
  .nvmrc
  .yarn/releases/yarn-3.2.4.cjs
  .yarnrc.yml
  package.json
  yarn.lock
Labels: dependencies

#355 feat: use error prop in date input component
  src/components/form/date-input/index.tsx
  src/components/form/date-input/style.ts
Labels: improvement
